import 'package:ishara/core/utils/assets.dart';

List<String> alphImages = [
  AssetsData.alefSign,
  AssetsData.ba2Sign,
  AssetsData.ta2Sign,
  AssetsData.tha2Sign,
  AssetsData.geemSign,
  AssetsData.haSign,
  AssetsData.khaSign,
  AssetsData.dalSign,
  AssetsData.zalSign,
  AssetsData.ra2Sign,
  AssetsData.zeenSign,
  AssetsData.seenSign,
  AssetsData.sheenSign,
  AssetsData.sadSign,
  AssetsData.dadSign,
  AssetsData.taahSign,
  AssetsData.zaahSign,
  AssetsData.aeenSign,
  AssetsData.khinSign,
  AssetsData.fa2Sign,
  AssetsData.qafSign,
  AssetsData.kafSign,
  AssetsData.lamSign,
  AssetsData.meemSign,
  AssetsData.noonSign,
  AssetsData.ha2Sign,
  AssetsData.wowSign,
  AssetsData.ya2Sign,
];