// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgwPUx8J-HLmqMl5MYx9FnivXX6wXSFhw',
    appId: '1:789055669976:web:8f8cadbea8d9da4510f9ad',
    messagingSenderId: '789055669976',
    projectId: 'ishara-2dfbd',
    authDomain: 'ishara-2dfbd.firebaseapp.com',
    storageBucket: 'ishara-2dfbd.firebasestorage.app',
    measurementId: 'G-Q7Y0X2SEEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR5567I6wR_Xwi88ZAfpEPRToOSQm58Sk',
    appId: '1:789055669976:android:32f676ea766fccd510f9ad',
    messagingSenderId: '789055669976',
    projectId: 'ishara-2dfbd',
    storageBucket: 'ishara-2dfbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2h4PskRN6toJpUVnNA6ElDc63T0cAwyM',
    appId: '1:789055669976:ios:0533254bd876aee110f9ad',
    messagingSenderId: '789055669976',
    projectId: 'ishara-2dfbd',
    storageBucket: 'ishara-2dfbd.firebasestorage.app',
    iosBundleId: 'com.example.ishara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2h4PskRN6toJpUVnNA6ElDc63T0cAwyM',
    appId: '1:789055669976:ios:0533254bd876aee110f9ad',
    messagingSenderId: '789055669976',
    projectId: 'ishara-2dfbd',
    storageBucket: 'ishara-2dfbd.firebasestorage.app',
    iosBundleId: 'com.example.ishara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgwPUx8J-HLmqMl5MYx9FnivXX6wXSFhw',
    appId: '1:789055669976:web:17f049a72448e3e710f9ad',
    messagingSenderId: '789055669976',
    projectId: 'ishara-2dfbd',
    authDomain: 'ishara-2dfbd.firebaseapp.com',
    storageBucket: 'ishara-2dfbd.firebasestorage.app',
    measurementId: 'G-1XKS6LWYMH',
  );
}
